// Generated by codegen/generate.mjs. Do not edit.
// Edit codegen/events/apis/cookies.mjs and run npm run generate.

import {browser} from "../browser";
import {handleListener} from "../utils";

export const onCookieChanged = (
    callback: Parameters<typeof chrome.cookies.onChanged.addListener>[0]
): (() => void) => {
    return handleListener(browser().cookies.onChanged, callback);
};
