// Generated by codegen/generate.mjs. Do not edit.
// Edit codegen/events/apis/tab-groups.mjs and run npm run generate.

import {browser} from "../browser";
import {handleListener} from "../utils";

import type {TabGroup, TabGroupRemoveInfo} from "./types";

export const onTabGroupCreated = (
    callback: (group: TabGroup) => void
): (() => void) => {
    return handleListener(browser().tabGroups.onCreated, callback);
};

export const onTabGroupUpdated = (
    callback: (group: TabGroup) => void
): (() => void) => {
    return handleListener(browser().tabGroups.onUpdated, callback);
};

export const onTabGroupMoved = (
    callback: (group: TabGroup) => void
): (() => void) => {
    return handleListener(browser().tabGroups.onMoved, callback);
};

export const onTabGroupRemoved = (
    callback: (group: TabGroup, removeInfo?: TabGroupRemoveInfo) => void
): (() => void) => {
    return handleListener(browser().tabGroups.onRemoved, callback);
};
