// Generated by codegen/index.mjs. Do not edit.
// Edit codegen/events/identity.mjs and run npm run generate.

import {browser} from "../browser";
import {handleListener} from "../utils";

export const onIdentitySignInChanged = (
    callback: Parameters<typeof chrome.identity.onSignInChanged.addListener>[0]
): (() => void) => {
    return handleListener(browser().identity.onSignInChanged, callback);
};
