// Generated by codegen/generate.mjs. Do not edit.
// Edit codegen/events/apis/runtime.mjs and run npm run generate.

import {browser} from "../browser";
import {handleListener} from "../utils";

export const onConnect = (
    callback: Parameters<typeof chrome.runtime.onConnect.addListener>[0]
): (() => void) => {
    return handleListener(browser().runtime.onConnect, callback);
};

export const onConnectExternal = (
    callback: Parameters<typeof chrome.runtime.onConnectExternal.addListener>[0]
): (() => void) => {
    return handleListener(browser().runtime.onConnectExternal, callback);
};

export const onInstalled = (
    callback: Parameters<typeof chrome.runtime.onInstalled.addListener>[0]
): (() => void) => {
    return handleListener(browser().runtime.onInstalled, callback);
};

export const onMessage = (
    callback: Parameters<typeof chrome.runtime.onMessage.addListener>[0]
): (() => void) => {
    return handleListener(browser().runtime.onMessage, callback);
};

export const onMessageExternal = (
    callback: Parameters<typeof chrome.runtime.onMessageExternal.addListener>[0]
): (() => void) => {
    return handleListener(browser().runtime.onMessageExternal, callback);
};

export const onRestartRequired = (
    callback: Parameters<typeof chrome.runtime.onRestartRequired.addListener>[0]
): (() => void) => {
    return handleListener(browser().runtime.onRestartRequired, callback);
};

export const onStartup = (
    callback: Parameters<typeof chrome.runtime.onStartup.addListener>[0]
): (() => void) => {
    return handleListener(browser().runtime.onStartup, callback);
};

export const onSuspend = (
    callback: Parameters<typeof chrome.runtime.onSuspend.addListener>[0]
): (() => void) => {
    return handleListener(browser().runtime.onSuspend, callback);
};

export const onSuspendCanceled = (
    callback: Parameters<typeof chrome.runtime.onSuspendCanceled.addListener>[0]
): (() => void) => {
    return handleListener(browser().runtime.onSuspendCanceled, callback);
};

export const onUpdateAvailable = (
    callback: Parameters<typeof chrome.runtime.onUpdateAvailable.addListener>[0]
): (() => void) => {
    return handleListener(browser().runtime.onUpdateAvailable, callback);
};

export const onUserScriptConnect = (
    callback: Parameters<typeof chrome.runtime.onUserScriptConnect.addListener>[0]
): (() => void) => {
    return handleListener(browser().runtime.onUserScriptConnect, callback);
};

export const onUserScriptMessage = (
    callback: Parameters<typeof chrome.runtime.onUserScriptMessage.addListener>[0]
): (() => void) => {
    return handleListener(browser().runtime.onUserScriptMessage, callback);
};
