// Generated by codegen/generate.mjs. Do not edit.
// Edit codegen/events/apis/management.mjs and run npm run generate.

import {browser} from "../browser";
import {handleListener} from "../utils";

export const onExtensionDisabled = (
    callback: Parameters<typeof chrome.management.onDisabled.addListener>[0]
): (() => void) => {
    return handleListener(browser().management.onDisabled, callback);
};

export const onExtensionEnabled = (
    callback: Parameters<typeof chrome.management.onEnabled.addListener>[0]
): (() => void) => {
    return handleListener(browser().management.onEnabled, callback);
};

export const onExtensionInstalled = (
    callback: Parameters<typeof chrome.management.onInstalled.addListener>[0]
): (() => void) => {
    return handleListener(browser().management.onInstalled, callback);
};

export const onExtensionUninstalled = (
    callback: Parameters<typeof chrome.management.onUninstalled.addListener>[0]
): (() => void) => {
    return handleListener(browser().management.onUninstalled, callback);
};
