// Generated by codegen/index.mjs. Do not edit.
// Edit codegen/events/web-request.mjs and run npm run generate.

import {browser} from "../browser";
import {safeListener} from "../utils";

export const onWebRequestAuthRequired = (
    callback: Parameters<typeof chrome.webRequest.onAuthRequired.addListener>[0],
    filter: Parameters<typeof chrome.webRequest.onAuthRequired.addListener>[1],
    extraInfoSpec?: Parameters<typeof chrome.webRequest.onAuthRequired.addListener>[2]
): (() => void) => {
    const event = browser().webRequest.onAuthRequired;
    const listener = safeListener(callback);

    event.addListener(listener, filter, extraInfoSpec);

    return () => event.removeListener(listener);
};

export const onWebRequestBeforeRedirect = (
    callback: Parameters<typeof chrome.webRequest.onBeforeRedirect.addListener>[0],
    filter: Parameters<typeof chrome.webRequest.onBeforeRedirect.addListener>[1],
    extraInfoSpec?: Parameters<typeof chrome.webRequest.onBeforeRedirect.addListener>[2]
): (() => void) => {
    const event = browser().webRequest.onBeforeRedirect;
    const listener = safeListener(callback);

    event.addListener(listener, filter, extraInfoSpec);

    return () => event.removeListener(listener);
};

export const onWebRequestBeforeRequest = (
    callback: Parameters<typeof chrome.webRequest.onBeforeRequest.addListener>[0],
    filter: Parameters<typeof chrome.webRequest.onBeforeRequest.addListener>[1],
    extraInfoSpec?: Parameters<typeof chrome.webRequest.onBeforeRequest.addListener>[2]
): (() => void) => {
    const event = browser().webRequest.onBeforeRequest;
    const listener = safeListener(callback);

    event.addListener(listener, filter, extraInfoSpec);

    return () => event.removeListener(listener);
};

export const onWebRequestBeforeSendHeaders = (
    callback: Parameters<typeof chrome.webRequest.onBeforeSendHeaders.addListener>[0],
    filter: Parameters<typeof chrome.webRequest.onBeforeSendHeaders.addListener>[1],
    extraInfoSpec?: Parameters<typeof chrome.webRequest.onBeforeSendHeaders.addListener>[2]
): (() => void) => {
    const event = browser().webRequest.onBeforeSendHeaders;
    const listener = safeListener(callback);

    event.addListener(listener, filter, extraInfoSpec);

    return () => event.removeListener(listener);
};

export const onWebRequestCompleted = (
    callback: Parameters<typeof chrome.webRequest.onCompleted.addListener>[0],
    filter: Parameters<typeof chrome.webRequest.onCompleted.addListener>[1],
    extraInfoSpec?: Parameters<typeof chrome.webRequest.onCompleted.addListener>[2]
): (() => void) => {
    const event = browser().webRequest.onCompleted;
    const listener = safeListener(callback);

    event.addListener(listener, filter, extraInfoSpec);

    return () => event.removeListener(listener);
};

export const onWebRequestErrorOccurred = (
    callback: Parameters<typeof chrome.webRequest.onErrorOccurred.addListener>[0],
    filter: Parameters<typeof chrome.webRequest.onErrorOccurred.addListener>[1],
    extraInfoSpec?: Parameters<typeof chrome.webRequest.onErrorOccurred.addListener>[2]
): (() => void) => {
    const event = browser().webRequest.onErrorOccurred;
    const listener = safeListener(callback);

    event.addListener(listener, filter, extraInfoSpec);

    return () => event.removeListener(listener);
};

export const onWebRequestHeadersReceived = (
    callback: Parameters<typeof chrome.webRequest.onHeadersReceived.addListener>[0],
    filter: Parameters<typeof chrome.webRequest.onHeadersReceived.addListener>[1],
    extraInfoSpec?: Parameters<typeof chrome.webRequest.onHeadersReceived.addListener>[2]
): (() => void) => {
    const event = browser().webRequest.onHeadersReceived;
    const listener = safeListener(callback);

    event.addListener(listener, filter, extraInfoSpec);

    return () => event.removeListener(listener);
};

export const onWebRequestResponseStarted = (
    callback: Parameters<typeof chrome.webRequest.onResponseStarted.addListener>[0],
    filter: Parameters<typeof chrome.webRequest.onResponseStarted.addListener>[1],
    extraInfoSpec?: Parameters<typeof chrome.webRequest.onResponseStarted.addListener>[2]
): (() => void) => {
    const event = browser().webRequest.onResponseStarted;
    const listener = safeListener(callback);

    event.addListener(listener, filter, extraInfoSpec);

    return () => event.removeListener(listener);
};

export const onWebRequestSendHeaders = (
    callback: Parameters<typeof chrome.webRequest.onSendHeaders.addListener>[0],
    filter: Parameters<typeof chrome.webRequest.onSendHeaders.addListener>[1],
    extraInfoSpec?: Parameters<typeof chrome.webRequest.onSendHeaders.addListener>[2]
): (() => void) => {
    const event = browser().webRequest.onSendHeaders;
    const listener = safeListener(callback);

    event.addListener(listener, filter, extraInfoSpec);

    return () => event.removeListener(listener);
};
