// Generated by codegen/generate.mjs. Do not edit.
// Edit codegen/availability/apis.mjs and run npm run generate.

import {browser} from "../browser";

export const isAvailableDownloads = (): boolean => {
    try {
        return Boolean(browser().downloads);
    } catch {
        return false;
    }
};
