// Generated by codegen/index.mjs. Do not edit.
// Edit codegen/events/downloads.mjs and run npm run generate.

import {browser} from "../browser";
import {handleListener} from "../utils";

export const onDownloadsChanged = (
    callback: Parameters<typeof chrome.downloads.onChanged.addListener>[0]
): (() => void) => {
    return handleListener(browser().downloads.onChanged, callback);
};

export const onDownloadsCreated = (
    callback: Parameters<typeof chrome.downloads.onCreated.addListener>[0]
): (() => void) => {
    return handleListener(browser().downloads.onCreated, callback);
};

export const onDownloadsDeterminingFilename = (
    callback: Parameters<typeof chrome.downloads.onDeterminingFilename.addListener>[0]
): (() => void) => {
    return handleListener(browser().downloads.onDeterminingFilename, callback);
};
