// Generated by codegen/index.mjs. Do not edit.
// Edit codegen/events/tabs.mjs and run npm run generate.

import {browser} from "../browser";
import {handleListener} from "../utils";

export const onTabActivated = (
    callback: Parameters<typeof chrome.tabs.onActivated.addListener>[0]
): (() => void) => {
    return handleListener(browser().tabs.onActivated, callback);
};

export const onTabAttached = (
    callback: Parameters<typeof chrome.tabs.onAttached.addListener>[0]
): (() => void) => {
    return handleListener(browser().tabs.onAttached, callback);
};

export const onTabCreated = (
    callback: Parameters<typeof chrome.tabs.onCreated.addListener>[0]
): (() => void) => {
    return handleListener(browser().tabs.onCreated, callback);
};

export const onTabDetached = (
    callback: Parameters<typeof chrome.tabs.onDetached.addListener>[0]
): (() => void) => {
    return handleListener(browser().tabs.onDetached, callback);
};

export const onTabHighlighted = (
    callback: Parameters<typeof chrome.tabs.onHighlighted.addListener>[0]
): (() => void) => {
    return handleListener(browser().tabs.onHighlighted, callback);
};

export const onTabMoved = (
    callback: Parameters<typeof chrome.tabs.onMoved.addListener>[0]
): (() => void) => {
    return handleListener(browser().tabs.onMoved, callback);
};

export const onTabRemoved = (
    callback: Parameters<typeof chrome.tabs.onRemoved.addListener>[0]
): (() => void) => {
    return handleListener(browser().tabs.onRemoved, callback);
};

export const onTabReplaced = (
    callback: Parameters<typeof chrome.tabs.onReplaced.addListener>[0]
): (() => void) => {
    return handleListener(browser().tabs.onReplaced, callback);
};

export const onTabUpdated = (
    callback: Parameters<typeof chrome.tabs.onUpdated.addListener>[0]
): (() => void) => {
    return handleListener(browser().tabs.onUpdated, callback);
};

export const onTabZoomChange = (
    callback: Parameters<typeof chrome.tabs.onZoomChange.addListener>[0]
): (() => void) => {
    return handleListener(browser().tabs.onZoomChange, callback);
};
