import assert from "node:assert/strict";
import {realpathSync} from "node:fs";
import {mkdir, readFile, writeFile} from "node:fs/promises";
import {dirname, resolve} from "node:path";
import {fileURLToPath} from "node:url";
import generateAvailability from "./availability/index.mjs";
import generateEvents from "./events/index.mjs";

const projectRoot = fileURLToPath(new URL("../", import.meta.url));
const header = "// Generated by codegen/generate.mjs. Do not edit.\n";

export function renderGeneratedFiles(modules) {
    const files = new Map();
    const exportNames = new Set();

    for (const module of modules) {
        const {namespace, name, exports: names, source} = module;
        assert.match(namespace, /^[a-z][a-zA-Z0-9]*$/, "Invalid generated namespace");
        assert.match(name, /^[a-z][a-z0-9]*(?:-[a-z0-9]+)*$/, "Invalid generated module name");
        assert.notEqual(name, "index", "Namespace indexes are maintained manually");
        const directory = namespace.replace(/[A-Z]/g, letter => `-${letter.toLowerCase()}`);
        const output = `src/api/${directory}/${name}.ts`;
        assert.ok(!files.has(output), `Duplicate generated module: ${output}`);

        for (const exportName of names) {
            assert.ok(!exportNames.has(exportName), `Duplicate generated export: ${exportName}`);
            exportNames.add(exportName);
        }

        files.set(output, header + source);
    }

    return files;
}

export async function generate({check = false} = {}) {
    const files = renderGeneratedFiles([
        ...generateAvailability(),
        ...generateEvents(),
    ]);

    const stale = [];

    for (const [relativePath, source] of files) {
        const path = resolve(projectRoot, relativePath);
        let current;

        try {
            current = await readFile(path, "utf8");
        } catch (error) {
            if (error.code !== "ENOENT") throw error;
        }

        if (current === source) continue;

        if (check) {
            stale.push(relativePath);
            continue;
        }

        await mkdir(dirname(path), {recursive: true});
        await writeFile(path, source, "utf8");
        console.log(`Generated ${relativePath}`);
    }

    if (stale.length) {
        throw new Error(`Generated sources are out of date: ${stale.join(", ")}. Run npm run generate.`);
    }
}

if (process.argv[1] && realpathSync(process.argv[1]) === fileURLToPath(import.meta.url)) {
    const args = process.argv.slice(2);
    assert.ok(args.length === 0 || (args.length === 1 && args[0] === "--check"), "Usage: codegen/generate.mjs [--check]");
    await generate({check: args.includes("--check")});
}
