// Generated by codegen/generate.mjs. Do not edit.
// Edit codegen/availability/apis.mjs and run npm run generate.

import {action} from "./api";

export const isAvailableAction = (): boolean => {
    try {
        return Boolean(action());
    } catch {
        return false;
    }
};
