// Generated by codegen/index.mjs. Do not edit.
// Edit codegen/events/action.mjs and run npm run generate.

import {handleListener} from "../utils";
import {type Action, action} from "./api";

export const onActionClicked = (
    callback: Parameters<typeof chrome.action.onClicked.addListener>[0]
): (() => void) => {
    return handleListener(action<Action>().onClicked, callback);
};

export const onActionUserSettingsChanged = (
    callback: Parameters<typeof chrome.action.onUserSettingsChanged.addListener>[0]
): (() => void) => {
    return handleListener(action<Action>().onUserSettingsChanged, callback);
};
