// Generated by codegen/index.mjs. Do not edit.
// Edit codegen/events/audio.mjs and run npm run generate.

import {browser} from "../browser";
import {handleListener} from "../utils";

export const onAudioDeviceListChanged = (
    callback: Parameters<typeof chrome.audio.onDeviceListChanged.addListener>[0]
): (() => void) => {
    return handleListener(browser().audio.onDeviceListChanged, callback);
};

export const onAudioLevelChanged = (
    callback: Parameters<typeof chrome.audio.onLevelChanged.addListener>[0]
): (() => void) => {
    return handleListener(browser().audio.onLevelChanged, callback);
};

export const onAudioMuteChanged = (
    callback: Parameters<typeof chrome.audio.onMuteChanged.addListener>[0]
): (() => void) => {
    return handleListener(browser().audio.onMuteChanged, callback);
};
