// Generated by codegen/index.mjs. Do not edit.
// Edit codegen/events/history.mjs and run npm run generate.

import {browser} from "../browser";
import {handleListener} from "../utils";

export const onHistoryVisited = (
    callback: Parameters<typeof chrome.history.onVisited.addListener>[0]
): (() => void) => {
    return handleListener(browser().history.onVisited, callback);
};

export const onHistoryVisitRemoved = (
    callback: Parameters<typeof chrome.history.onVisitRemoved.addListener>[0]
): (() => void) => {
    return handleListener(browser().history.onVisitRemoved, callback);
};
