// Generated by codegen/generate.mjs. Do not edit.
// Edit codegen/events/apis/permissions.mjs and run npm run generate.

import {browser} from "../browser";
import {handleListener} from "../utils";

export const onPermissionsAdded = (
    callback: Parameters<typeof chrome.permissions.onAdded.addListener>[0]
): (() => void) => {
    return handleListener(browser().permissions.onAdded, callback);
};

export const onPermissionsRemoved = (
    callback: Parameters<typeof chrome.permissions.onRemoved.addListener>[0]
): (() => void) => {
    return handleListener(browser().permissions.onRemoved, callback);
};
