// Generated by codegen/generate.mjs. Do not edit.
// Edit codegen/events/apis/web-navigation.mjs and run npm run generate.

import {browser} from "../browser";
import {handleListener, safeListener} from "../utils";

export const onWebNavigationBeforeNavigate = (
    callback: Parameters<typeof chrome.webNavigation.onBeforeNavigate.addListener>[0],
    filters?: Parameters<typeof chrome.webNavigation.onBeforeNavigate.addListener>[1]
): (() => void) => {
    const event = browser().webNavigation.onBeforeNavigate;
    const listener = safeListener(callback);

    event.addListener(listener, filters);

    return () => event.removeListener(listener);
};

export const onWebNavigationCommitted = (
    callback: Parameters<typeof chrome.webNavigation.onCommitted.addListener>[0],
    filters?: Parameters<typeof chrome.webNavigation.onCommitted.addListener>[1]
): (() => void) => {
    const event = browser().webNavigation.onCommitted;
    const listener = safeListener(callback);

    event.addListener(listener, filters);

    return () => event.removeListener(listener);
};

export const onWebNavigationCompleted = (
    callback: Parameters<typeof chrome.webNavigation.onCompleted.addListener>[0],
    filters?: Parameters<typeof chrome.webNavigation.onCompleted.addListener>[1]
): (() => void) => {
    const event = browser().webNavigation.onCompleted;
    const listener = safeListener(callback);

    event.addListener(listener, filters);

    return () => event.removeListener(listener);
};

export const onWebNavigationCreatedNavigationTarget = (
    callback: Parameters<typeof chrome.webNavigation.onCreatedNavigationTarget.addListener>[0],
    filters?: Parameters<typeof chrome.webNavigation.onCreatedNavigationTarget.addListener>[1]
): (() => void) => {
    const event = browser().webNavigation.onCreatedNavigationTarget;
    const listener = safeListener(callback);

    event.addListener(listener, filters);

    return () => event.removeListener(listener);
};

export const onWebNavigationDOMContentLoaded = (
    callback: Parameters<typeof chrome.webNavigation.onDOMContentLoaded.addListener>[0],
    filters?: Parameters<typeof chrome.webNavigation.onDOMContentLoaded.addListener>[1]
): (() => void) => {
    const event = browser().webNavigation.onDOMContentLoaded;
    const listener = safeListener(callback);

    event.addListener(listener, filters);

    return () => event.removeListener(listener);
};

export const onWebNavigationErrorOccurred = (
    callback: Parameters<typeof chrome.webNavigation.onErrorOccurred.addListener>[0],
    filters?: Parameters<typeof chrome.webNavigation.onErrorOccurred.addListener>[1]
): (() => void) => {
    const event = browser().webNavigation.onErrorOccurred;
    const listener = safeListener(callback);

    event.addListener(listener, filters);

    return () => event.removeListener(listener);
};

export const onWebNavigationHistoryStateUpdated = (
    callback: Parameters<typeof chrome.webNavigation.onHistoryStateUpdated.addListener>[0],
    filters?: Parameters<typeof chrome.webNavigation.onHistoryStateUpdated.addListener>[1]
): (() => void) => {
    const event = browser().webNavigation.onHistoryStateUpdated;
    const listener = safeListener(callback);

    event.addListener(listener, filters);

    return () => event.removeListener(listener);
};

export const onWebNavigationReferenceFragmentUpdated = (
    callback: Parameters<typeof chrome.webNavigation.onReferenceFragmentUpdated.addListener>[0],
    filters?: Parameters<typeof chrome.webNavigation.onReferenceFragmentUpdated.addListener>[1]
): (() => void) => {
    const event = browser().webNavigation.onReferenceFragmentUpdated;
    const listener = safeListener(callback);

    event.addListener(listener, filters);

    return () => event.removeListener(listener);
};

export const onWebNavigationTabReplaced = (
    callback: Parameters<typeof chrome.webNavigation.onTabReplaced.addListener>[0]
): (() => void) => {
    return handleListener(browser().webNavigation.onTabReplaced, callback);
};
