// Generated by codegen/index.mjs. Do not edit.
// Edit codegen/events/notifications.mjs and run npm run generate.

import {browser} from "../browser";
import {handleListener} from "../utils";

export const onNotificationsButtonClicked = (
    callback: Parameters<typeof chrome.notifications.onButtonClicked.addListener>[0]
): (() => void) => {
    return handleListener(browser().notifications.onButtonClicked, callback);
};

export const onNotificationsClicked = (
    callback: Parameters<typeof chrome.notifications.onClicked.addListener>[0]
): (() => void) => {
    return handleListener(browser().notifications.onClicked, callback);
};

export const onNotificationsClosed = (
    callback: Parameters<typeof chrome.notifications.onClosed.addListener>[0]
): (() => void) => {
    return handleListener(browser().notifications.onClosed, callback);
};

export const onNotificationsPermissionLevelChanged = (
    callback: Parameters<typeof chrome.notifications.onPermissionLevelChanged.addListener>[0]
): (() => void) => {
    return handleListener(browser().notifications.onPermissionLevelChanged, callback);
};
