// Generated by codegen/generate.mjs. Do not edit.
// Edit codegen/availability/apis.mjs and run npm run generate.

import {sidebarAction, sidePanel} from "./api";

export const isAvailableSidebar = (): boolean => {
    try {
        return Boolean(sidePanel() || sidebarAction());
    } catch {
        return false;
    }
};
