// Generated by codegen/generate.mjs. Do not edit.
// Edit codegen/events/apis/declarative-net-request.mjs and run npm run generate.

import {browser} from "../browser";
import {handleListener} from "../utils";

export const onDnrRuleMatchedDebug = (
    callback: Parameters<typeof chrome.declarativeNetRequest.onRuleMatchedDebug.addListener>[0]
): (() => void) => {
    return handleListener(browser().declarativeNetRequest.onRuleMatchedDebug, callback);
};
