// Generated by codegen/generate.mjs. Do not edit.
// Edit codegen/events/apis/bookmarks.mjs and run npm run generate.

import {browser} from "../browser";
import {handleListener} from "../utils";

export const onBookmarkCreated = (
    callback: Parameters<typeof chrome.bookmarks.onCreated.addListener>[0]
): (() => void) => {
    return handleListener(browser().bookmarks.onCreated, callback);
};

export const onBookmarkRemoved = (
    callback: Parameters<typeof chrome.bookmarks.onRemoved.addListener>[0]
): (() => void) => {
    return handleListener(browser().bookmarks.onRemoved, callback);
};

export const onBookmarkChanged = (
    callback: (id: string, changeInfo: {title?: string; url?: string}) => void
): (() => void) => {
    return handleListener(browser().bookmarks.onChanged, callback);
};

export const onBookmarkMoved = (
    callback: Parameters<typeof chrome.bookmarks.onMoved.addListener>[0]
): (() => void) => {
    return handleListener(browser().bookmarks.onMoved, callback);
};

export const onBookmarkChildrenReordered = (
    callback: Parameters<typeof chrome.bookmarks.onChildrenReordered.addListener>[0]
): (() => void) => {
    return handleListener(browser().bookmarks.onChildrenReordered, callback);
};

export const onBookmarksImportBegan = (
    callback: Parameters<typeof chrome.bookmarks.onImportBegan.addListener>[0]
): (() => void) => {
    return handleListener(browser().bookmarks.onImportBegan, callback);
};

export const onBookmarksImportEnded = (
    callback: Parameters<typeof chrome.bookmarks.onImportEnded.addListener>[0]
): (() => void) => {
    return handleListener(browser().bookmarks.onImportEnded, callback);
};
