// Generated by codegen/generate.mjs. Do not edit.
// Edit codegen/events/apis/alarms.mjs and run npm run generate.

import {browser} from "../browser";
import {handleListener} from "../utils";

export const onAlarm = (
    callback: Parameters<typeof chrome.alarms.onAlarm.addListener>[0]
): (() => void) => {
    return handleListener(browser().alarms.onAlarm, callback);
};
