export default [
    {namespace: "action", template: "action"},
    {namespace: "alarms"},
    {namespace: "audio"},
    {namespace: "browsingData"},
    {namespace: "commands"},
    {namespace: "contextMenus"},
    {namespace: "cookies"},
    {namespace: "documentScan"},
    {namespace: "downloads"},
    {namespace: "extension"},
    {namespace: "history"},
    {namespace: "i18n"},
    {namespace: "identity"},
    {namespace: "idle"},
    {namespace: "management"},
    {namespace: "notifications"},
    {namespace: "offscreen"},
    {namespace: "permissions"},
    {namespace: "runtime"},
    {namespace: "scripting"},
    {namespace: "search"},
    {namespace: "sidebar", template: "sidebar"},
    {namespace: "tabCapture"},
    {namespace: "tabs"},
    {namespace: "userScripts"},
    {namespace: "webNavigation"},
    {namespace: "webRequest"},
    {namespace: "windows"},
];
