// Generated by codegen/index.mjs. Do not edit.
// Edit codegen/events/idle.mjs and run npm run generate.

import {browser} from "../browser";
import {handleListener} from "../utils";

export const onIdleStateChanged = (
    callback: Parameters<typeof chrome.idle.onStateChanged.addListener>[0]
): (() => void) => {
    return handleListener(browser().idle.onStateChanged, callback);
};
