// Generated by codegen/index.mjs. Do not edit.
// Edit codegen/events/commands.mjs and run npm run generate.

import {browser} from "../browser";
import {handleListener} from "../utils";

export const onCommand = (
    callback: Parameters<typeof chrome.commands.onCommand.addListener>[0]
): (() => void) => {
    return handleListener(browser().commands.onCommand, callback);
};
