// Generated by codegen/generate.mjs. Do not edit.
// Edit codegen/events/apis/context-menus.mjs and run npm run generate.

import {browser} from "../browser";
import {handleListener} from "../utils";

export const onContextMenusClicked = (
    callback: Parameters<typeof chrome.contextMenus.onClicked.addListener>[0]
): (() => void) => {
    return handleListener(browser().contextMenus.onClicked, callback);
};
