// Generated by codegen/generate.mjs. Do not edit.
// Edit codegen/events/apis/windows.mjs and run npm run generate.

import {browser} from "../browser";
import {handleListener, safeListener} from "../utils";

import type {WindowEventFilter} from "./types";

export const onWindowBoundsChanged = (
    callback: Parameters<typeof chrome.windows.onBoundsChanged.addListener>[0]
): (() => void) => {
    return handleListener(browser().windows.onBoundsChanged, callback);
};

export const onWindowCreated = (
    callback: Parameters<typeof chrome.windows.onCreated.addListener>[0],
    filter?: WindowEventFilter
): (() => void) => {
    const event = browser().windows.onCreated;
    const listener = safeListener(callback);
    const args: Parameters<typeof chrome.windows.onCreated.addListener> = [listener];

    if (filter) {
        args.push(filter);
    }

    event.addListener(...args);

    return () => event.removeListener(listener);
};

export const onWindowFocusChanged = (
    callback: Parameters<typeof chrome.windows.onFocusChanged.addListener>[0],
    filter?: WindowEventFilter
): (() => void) => {
    const event = browser().windows.onFocusChanged;
    const listener = safeListener(callback);
    const args: Parameters<typeof chrome.windows.onFocusChanged.addListener> = [listener];

    if (filter) {
        args.push(filter);
    }

    event.addListener(...args);

    return () => event.removeListener(listener);
};

export const onWindowRemoved = (
    callback: Parameters<typeof chrome.windows.onRemoved.addListener>[0],
    filter?: WindowEventFilter
): (() => void) => {
    const event = browser().windows.onRemoved;
    const listener = safeListener(callback);
    const args: Parameters<typeof chrome.windows.onRemoved.addListener> = [listener];

    if (filter) {
        args.push(filter);
    }

    event.addListener(...args);

    return () => event.removeListener(listener);
};
