// Generated by codegen/generate.mjs. Do not edit.
// Edit codegen/events/apis/tab-capture.mjs and run npm run generate.

import {browser} from "../browser";
import {handleListener} from "../utils";

export const onCaptureStatusChanged = (
    callback: Parameters<typeof chrome.tabCapture.onStatusChanged.addListener>[0]
): (() => void) => {
    return handleListener(browser().tabCapture.onStatusChanged, callback);
};
