name: Release Preview

on:
  push:
    branches:
      - 'release/**'
      - 'hotfix/**'

permissions:
  contents: write
  packages: read

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    secrets: inherit

  preview:
    name: Release Preview via release-it
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Configure Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Install dependencies
        env:
          HUSKY: 0
        run: npm ci

      - name: Detect latest tag
        run: echo "LATEST_TAG=$(git tag --list 'v*' --sort=-v:refname | head -n 1)" >> $GITHUB_ENV

      - name: Release (preview)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ -n "${LATEST_TAG}" ]; then
            npm run release:preview -- --plugins.@release-it/conventional-changelog.gitRawCommitsOpts.from="${LATEST_TAG}"
          else
            npm run release:preview
          fi
